<?php
/*
 * @category    Hetic
 * @package     Hetic_Magento
 * @copyright   Copyright (c) 2016 Hetic
 * @author      Matthieu Demunck
 */
?>
<?php
$_categories = Mage::getModel('catalog/category')
        ->getCollection()
        ->addAttributeToSelect('*')
        ->addIsActiveFilter()
        ->addUrlRewriteToResult();
$_catalogCatgoryHelper = Mage::helper('catalog/category');
?>
<?php $currentCategory = Mage::registry('current_category') ?>
<?php if (count($_categories) > 0): ?>
		<?php foreach($_categories as $_category): ?>
				<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
				<?php $_subcategories = $_category->getChildrenCategories() ?>
				<?php if (count($_subcategories) > 0): ?>
						<?php foreach($_subcategories as $_subcategory): ?>
							<div class="col-sm-4">
								<a class="article" href="<?php echo $_subcategory->getUrl($_subcategory); ?>">
									<div class="title-category">
										<?php echo $_subcategory->getName() ?>
									</div>
								</a>
							</div>
						<?php endforeach; ?>
				<?php endif; ?>
		<?php endforeach; ?>
<?php endif; ?>